[browser]
gatherUsageStats = false

[server]
headless = true
maxUploadSize = 20

[theme]
base = "light"
primaryColor = "#1178C9"
backgroundColor = "#F5F7F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172330"
